language: java
notifications:
  slack:
    secure: i5vYi8uMTKYQ6UHBvTLuGiPKD2Kf4to/k2Z699MU2IDesNq5k0/pMKKvURRqSaDVwUdQjWWrgzdUe8MAB5UcpPasS4znhxw2GBGj/dK5Zm0+lysMqB/fvOv+CXJnbB/AIxFZehb+0/hukYvr1Z2I6sKQ2ZV1K/sQxKPETd2oCCsBTN391y8td1BZo+bA6ncXziJ3E6GXbCE66MAoWegq4lOT679z4wgosQstlveof69NkXZ71ZeB7rhBo43RPXa/X0BpHyoqkilTyEWLvreeWfE6tO4vo0q5PIJU0fa23j6AN0CJi90dCMXSSoj0QyJy7Z02/t94psTx96dAzyRbij6CwtPkdBYhcyX/8lsRD0vx8OwPvn+7f4c9SJzhfYXjss8olSyBiumHTxWXRlf4Yu+MPznnwSACi4rR5P+fuNaBx3TQ4M8s2gRX6tDJBgYI+GiDDENrCyYFtliEbss+PnaZT5jNQDwOFFfoCuxXAI49Rgthw4sW+Vd3uUx3qcHV80TLlAeQeatL2WIHJkF5N2zAhrB9N8k6nD2KqL05HZ9ipln+R+Da5S85fQPgD+wf2m8GBTJoZ0TRhz8+MbG2zS6AY6AFK6DyBSIdVGxsykizQ4HSZXAzV8UsJnyavZJHrrG2ioOJ4vYLknZ60fX7rppM1LfNFM84FtpjcR7qVNA=
deploy:
  provider: releases
  api_key:
    secure: KJWPw+aaS4dIbV4mbowfdI1k6L9376T9c3TXvh/gjDfypkmsL1JGDVar8c55ZC01dXFP4/uqb8sHsvZRK1fwHAECkKmIsuxnC4P4yfLfAgYn3//4eXQAfB7ibj/K06Hl7tHMUKvnrPRzJ+YpswBjZrKdye6nYIRt8MavNMdhaZF4n43jB0giMvzVqGp0PyNyLQMn7kBF4bH007Z6BUvDM7fOY3HJaoB+rWJO25sd945mazeTnMEx/VZdpAQDIdqyZupWzv8JuAhu8hEeaOgysqzfYi6Na3VIesXoB+mew9ymNR9a2gDyw9QQB2LWjOgkSOsOFVuO5B0KJMTRsEAtguW33R0WFevFVa0LT/oq9bZ/L9DI3k0msJpqwygrUjVdZgKb9c6xV948rQ+riZoAXWzLrXpO0jHKVfsd61LTuwfkuipxv3CNmyOHYURYXJ8kDeiH2xOUGO2HYXjO/I1xe5JcABC10GN/b9Ndo+Jx8UELgixKFQruwNKWU1y7eBujfFbpJsDuCLriqcObexMUWgMSj5Ar2YmgBUpvJlwWdLlX9lRUiEMgKFDzTa3kPV514Cf+jlWew3KkumB35By2W1YJAVrudL1hGc6vVsfKy9nvRQ0P1JKQn/8O8vLz8Co8W1OkpGeSYz7hgxk5FFITVL/0m3RUpAPdISLSVvwjpNQ=
  file: build/libs/xlr-circleci-plugin-1.1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-circleci-plugin
