language: java
notifications:
  hipchat:
    rooms:
      secure: LhlTbdNGSBncacJGPzL581Ld8w1JXyZ7GM4SFp7GGiPSkwX8d2t5cK8/BgY7viX2mjbdYaqT3wt+IUUQTRjuYyQaM2rHmqvZnnvz+vEqoye9cDGvzF3eV4CLuX1LTD4fui+cz0Kq4TucHuof4hd2Fk0eArk8tqqrQMZEiypnaakuTh0Kq/0DfJwk1GYbQAW+4swyL0+ETz9yrz3tg01aHS324b9DkGrwnSbDxzUmCeUqFVl3hcaXit40JFo55xxad6fImhL0vm1VHKPu83tri+bfuPfTJgQV8iwoOKgA8iQocRG6tzjpomG2tv8k9EDv2YbFmAhFfNSmxiBPtreZi9HBeSGn5dnm14zXP7KSihAgMrRVKyxH+8H/RbFDmyqEwqvP4r7CNzl0YKxZ6VB64zc2+QPNjjiyWazdl1yKA5bD+glmH4nZdm5UPPEMEZCcUzMnVxldBKQ9IEZ0Z3YvjN1qZ7hwSiGVlxrz3neDbukjU++OZO7vYxCCLib0tU72XDxF6giqg07uE4BMSSpEhn7S7kmiDrj0B1Z+gPHcuZSjgmyn4XMhFkQzhQNnmld0A+eATNxSxWRCFMpLyqoYf/pb1hFW356yDSCZZcgLXEuBN9qYNx1bhfGnTOsqEehi8iXtOOsDVo5GX+vIQop0N077Pa7V70nmWJSa1zmmn6I=
deploy:
  provider: releases
  api_key:
    secure: KJWPw+aaS4dIbV4mbowfdI1k6L9376T9c3TXvh/gjDfypkmsL1JGDVar8c55ZC01dXFP4/uqb8sHsvZRK1fwHAECkKmIsuxnC4P4yfLfAgYn3//4eXQAfB7ibj/K06Hl7tHMUKvnrPRzJ+YpswBjZrKdye6nYIRt8MavNMdhaZF4n43jB0giMvzVqGp0PyNyLQMn7kBF4bH007Z6BUvDM7fOY3HJaoB+rWJO25sd945mazeTnMEx/VZdpAQDIdqyZupWzv8JuAhu8hEeaOgysqzfYi6Na3VIesXoB+mew9ymNR9a2gDyw9QQB2LWjOgkSOsOFVuO5B0KJMTRsEAtguW33R0WFevFVa0LT/oq9bZ/L9DI3k0msJpqwygrUjVdZgKb9c6xV948rQ+riZoAXWzLrXpO0jHKVfsd61LTuwfkuipxv3CNmyOHYURYXJ8kDeiH2xOUGO2HYXjO/I1xe5JcABC10GN/b9Ndo+Jx8UELgixKFQruwNKWU1y7eBujfFbpJsDuCLriqcObexMUWgMSj5Ar2YmgBUpvJlwWdLlX9lRUiEMgKFDzTa3kPV514Cf+jlWew3KkumB35By2W1YJAVrudL1hGc6vVsfKy9nvRQ0P1JKQn/8O8vLz8Co8W1OkpGeSYz7hgxk5FFITVL/0m3RUpAPdISLSVvwjpNQ=
  file: build/libs/xlr-circleci-plugin-1.1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-circleci-plugin
